### ISSUE TITLE
An interesting but useless App. NICE TRY

### ISSUE THREAD

**Issue by NanyangTaiji** [MatteoCarnelos/screenparty#1]

**Comment by matteocarnelos** [comment]
Hi Nanyang, thanks for your feedback.
This app was meant to be a demonstration of the capabilities of smartphones for the Embedded Systems course of the University of Padua and we thought that this would have been a nice idea.
The usability of the app is questionable right now but maybe we can develop it to make it more useful in the future, who knows...
